// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StadiumAnalytics.Infrastructure.Data;

#nullable disable

namespace StadiumAnalytics.Infrastructure.Data.Migrations
{
    [DbContext(typeof(StadiumDbContext))]
    partial class StadiumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("StadiumAnalytics.Infrastructure.Data.Entities.FailedEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FailedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gate")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfPeople")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FailedEvents", (string)null);
                });

            modelBuilder.Entity("StadiumAnalytics.Infrastructure.Data.Entities.GateSensorEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Gate", "Timestamp", "Type")
                        .IsUnique()
                        .HasDatabaseName("IX_GateSensorEvents_Gate_Timestamp_Type");

                    b.HasIndex("Gate", "Type", "Timestamp")
                        .HasDatabaseName("IX_GateSensorEvents_Gate_Type_Timestamp");

                    b.ToTable("GateSensorEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_GateSensorEvents_Gate", "Gate IN ('GateA', 'GateB', 'GateC', 'GateD', 'GateE')");

                            t.HasCheckConstraint("CK_GateSensorEvents_NumberOfPeople", "NumberOfPeople > 0");

                            t.HasCheckConstraint("CK_GateSensorEvents_Type", "Type IN ('Enter', 'Leave')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
